export enum MimeTypes {
	jpeg = "image/jpeg",
	png = "image/png",
	gif = "image/gif",
	webp = "image/webp",
	mp4 = "video/mp4",
	mp3 = "audio/mpeg",
	pdf = "application/pdf",
	doc = "application/msword",
	docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	xls = "application/vnd.ms-excel",
	xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	ppt = "application/vnd.ms-powerpoint",
	pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	txt = "text/plain",
	html = "text/html",
	css = "text/css",
	json = "application/json",
	xml = "application/xml",
	zip = "application/zip",
	rar = "application/x-rar-compressed",
}
